backend:
  name: github
  repo: sajclarke/nunjucks-netlifycms

media_folder: media_folder

collections:
  - name: post
    label: Post
    folder: posts
    extension: json
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: text }
